import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Nav from "@/components/nav";
import { Toaster } from "@/components/ui/toaster";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const userIdCookie = cookieStore.get("userId")?.value;

  return (
    <html lang="en">
      <body className={cn(inter.className, "m-8 space-y-1.5")}>
        <Nav currentUserId={userIdCookie} />
        <main className={"space-y-8"}>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
